### ISSUE TITLE
Resources pack?

### ISSUE THREAD

**Issue by Nick31629** [Michelo11/Phone#1]
Where can we download the resources pack?
[My bug's screenshot](https://i.feathermc.com/wx8PnSnD.png)

**Comment by Michelo11** [comment]
https://github.com/Michelo11/Phone/releases/download/v1.0/Custom.Phone.zip

**Comment by Nick31629** [comment]
it doesn't work

**Comment by Michelo11** [comment]
What minecraft version are you using?

**Comment by Nick31629** [comment]
1.20.4 feather client

**Comment by Michelo11** [comment]
are you using optifine?

**Comment by Nick31629** [comment]
![immagine_2024-05-28_195058660](https://github.com/Michelo11/Phone/assets/87989607/91cd1480-cf6b-482f-8e42-5b393eab0f8f)
I've it, but disabled

**Comment by Michelo11** [comment]
This required to see the modal

**Comment by Nick31629** [comment]
![image](https://github.com/Michelo11/Phone/assets/87989607/12bf7f6d-ac53-4cae-b9eb-9d0b80200f75)
actived, but still doesn't work :(

**Comment by Nick31629** [comment]
should I restart the client?

**Comment by Michelo11** [comment]
Probably yes

**Comment by Nick31629** [comment]
![image](https://github.com/Michelo11/Phone/assets/87989607/6ad47af9-44e8-4ce1-b391-b0538f0936db)
gone :D

**Comment by Nick31629** [comment]
gone
